// src/app/layout.tsx
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google'; // Corrigido para importação correta
import './globals.css';
import LayoutWrapper from '@/components/LayoutWrapper'; // Importe o novo componente

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*
          O LayoutWrapper agora cuida da lógica de exibir ou não o Header.
          Ele recebe os "children" (o conteúdo da sua página) e os renderiza.
        */}
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}